[package]
name = "generator"
version = "0.1.0"
edition = "2021"

[dependencies]
bms-writer = { version = "0.1.0", path = "../bms-writer" }
keysound-gen = { path = "../keysound-gen" }

[dev-dependencies]
approx = "0.5.1"
